site_name: 'CoderDojo TC Python'
nav:
  - Trinket:
    - Turtle Graphics: trinket/01-turtle-graphics
    - Simple Square: trinket/02-simple-square
    - Variables: trinket/03-variables
  - Jupyter:
    - Setup: jupyter/01-setup
    - Draw Figure: jupyter/02-draw-figure
  - Contributing:
    - How to Contribute Examples: contribute.md
  - Contact:
    - Contact: contact.md

site_description: 'Resources for teaching Python to CoderDojo Twin Cities students.'
site_author: 'Dan McCreary'
repo_name: 'python'
repo_url: 'https://github.com/CoderDojoTC/python'
edit_uri: 'blob/master/docs'
theme:
  name: mkdocs
  palette:
    primary: 'amber'
    accent: 'amber'
  feature:
    tabs: true
  custom_dir: 'theme'
  include_sidebar: true
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - codehilite:
      linenums: true
plugins:
    - search
