site_name: 'CoderDojo TC Python'
nav:
  - Trinket:
    - Introduction: trinket/00-introduction.md
    - Turtle Graphics: trinket/01-turtle-graphics.md
    - Simple Square: trinket/02-simple-square.md
    - Variables: trinket/03-variables.md
    - Loops: trinket/04-loops.md
    - Conditional: trinket/05-conditionals.md
    - Functions: trinket/06-functions.md
    - Flower: trinket/07-flower.md
    - Function Parameters: trinket/07-function-parameters.md
    - Lists: trinket/08-list.md
    - Random Numbers: trinket/08-random.md
    - Input: trinket/11-input.md
    - Recursion: trinket/12-recursion.md
  - Repl.it:
    - Square: repl/02-square.md
    - Flower: repl/07-flower.md
    - Recursion: repl/12-recursion.md
  - Jupyter:
    - Setup Turtle on Jupyter: jupyter/01-setup.md
    - Drawing Box Labs: jupyter/02-draw-box.md
    - Drawing Figure: jupyter/02-draw-figure.md
    - Setup Canvas on Jupyter Lab: jupyter/02-canvas-setup.md
    - Canvas Color Bars: jupyter/20-canvas-color-bars.md
  - Pi:
    - Python on Raspberry Pi: pi/01-intro.md
  - Advanced Python:
    - Stock Ticker Analysis: advanced/stocks.md
    
  - Contributing:
    - How to Contribute Examples: contribute.md
  - Contact:
    - Contact: contact.md

site_description: 'Resources for teaching Python to CoderDojo Twin Cities students.'
site_author: 'Dan McCreary'
repo_name: 'python'
repo_url: 'https://github.com/CoderDojoTC/python'
edit_uri: 'blob/master/docs'
theme:
  name: material
  logo: img/coderdojo-logo-dark-bg-light-text.png
  palette:
    primary: '#642580'
    accent: '#41BAC1'
  feature:
    tabs: true
  custom_dir: 'theme'
  include_sidebar: true
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - codehilite:
      linenums: true
plugins:
    - search
markdown_extensions:
  - codehilite
