site_name: 'Dan_McCreary_ATC_Presetnations'
nav:
  - Home:
    - Home: home/home.md
  - Documentation:
    - Documentation: documentation/documentation.md
  - Getting Started:
    - Getting Started: getting-started/getting-started.md
  - Support:
    - Support: support/support.md
    - Team: support/team.md
    - Contact: support/contact.md

repo_name: 'atc_presentations2'
repo_url: 'https://github.optum.com/dmccrea1/atc_presentations2'
edit_uri: 'blob/master/docs'
copyright: 'Copyright &copy; 2020 Optum'
theme:
  name: material
  palette:
    primary: 'amber'
    accent: 'amber'
  feature:
    tabs: true
  custom_dir: 'theme'
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - codehilite:
      linenums: true
