site_name: 'CoderDojo Twin Cities Python Resources'
nav:
  - Home:
    - Home: home.md
  - Contact:
    - Contact: contact.md

repo_name: 'python'
repo_url: 'https://github.com/CoderDojoTC/python'
edit_uri: 'blob/master/docs'
theme:
  name: mkdocs
  palette:
    primary: 'amber'
    accent: 'amber'
  feature:
    tabs: true
  custom_dir: 'theme'
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - codehilite:
      linenums: true
