site_name: 'CoderDojo Twin Cities Python Resources'
nav:
  - Home:
    - Home: index.md
  - Contact:
    - Contact: contact.md

site_description: 'Resources for teaching Python to CoderDojo students.'
site_author: 'Dan McCreary'
repo_name: 'python'
repo_url: 'https://github.com/CoderDojoTC/python'
edit_uri: 'blob/master/docs'
theme:
  name: mkdocs
  palette:
    primary: 'amber'
    accent: 'amber'
  feature:
    tabs: true
  custom_dir: 'theme'
  include_sidebar: true
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - codehilite:
      linenums: true
plugins:
    - search
