site_name: 'CoderDojo TC Python'
nav:
  - Trinket:
    - Turtle Graphics: trinket/01-turtle-graphics
    - Simple Square: trinket/02-simple-square
    - Variables: trinket/03-variables
    - Loops: trinket/03-variables
    - Conditional: trinket/05-conditionals
    - Functions: trinket/06-functions
    - Function Parameters: trinket/07-function-parameters
    - Random Numbers: trinket/08-random
  - Jupyter:
    - Setup Turtle on Jupyter: jupyter/01-setup
    - Drawing Box Labs: jupyter/02-draw-box
    - Drawing Figure: jupyter/02-draw-figure
    - Setup Canvas on Jupyter Lab: jupyter/02-canvas-setup
    - Canvas Color Bars: jupyter/20-canvas-color-bars

    
  - Contributing:
    - How to Contribute Examples: contribute.md
  - Contact:
    - Contact: contact.md

site_description: 'Resources for teaching Python to CoderDojo Twin Cities students.'
site_author: 'Dan McCreary'
repo_name: 'python'
repo_url: 'https://github.com/CoderDojoTC/python'
edit_uri: 'blob/master/docs'
theme:
  name: mkdocs
  palette:
    primary: 'amber'
    accent: 'amber'
  feature:
    tabs: true
  custom_dir: 'theme'
  include_sidebar: true
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - codehilite:
      linenums: true
plugins:
    - search
markdown_extensions:
  - codehilite
