name: Build Documentation using MkDocs

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
    paths:
      - '**.yml'
  pull_request:
    branches: [master]

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  build:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout Master
        uses: actions/checkout@v3
        - uses: actions/checkout@v2
          if: github.event_name == 'pull_request'
          with:
            fetch-depth: 0
            ref: ${{ github.event.pull_request.head.ref }}

        - uses: actions/checkout@v3
          if: github.event_name == 'push'
          with:
            fetch-depth: 0

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material

      - name: Check
        run: |
          pwd
          ls -la
      - name: Deploy
   #     with:
   #      branch: master # The branch the action should deploy to.
        run: |
          git pull
          mkdocs gh-deploy
